# Generated by Django 5.0.1 on 2024-04-03 18:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('distance', models.PositiveIntegerField()),
                ('city', models.SmallIntegerField(blank=True, choices=[(0, 'Madinah'), (1, 'Makkah')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiyalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.SmallIntegerField(blank=True, choices=[(0, 'Private'), (1, 'Sharing'), (2, 'Double'), (3, 'Tripple'), (4, 'Quadripple')])),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('riyal_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('riyal_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pkr_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ticket.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ticket.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pnr', models.CharField(max_length=100)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('passenger', models.CharField(blank=True, max_length=255, null=True)),
                ('travel_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('airline', models.CharField(blank=True, max_length=255, null=True)),
                ('sale', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ticket_type', models.CharField(choices=[('IS', 'Issues'), ('RF', 'Refund'), ('RI', 'ReIssue'), ('VO', 'Void')], default='Issues', max_length=2)),
                ('narration', models.TextField(blank=True, default='', null=True)),
                ('excel_id', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.customer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riyal_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sale', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sale_pkr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_pkr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('visa_type', models.CharField(choices=[('DV', 'Dubai Visit'), ('SV', 'Saudia Visit'), ('DW', 'Dubai Work'), ('SW', 'Saudia Work'), ('UV', 'Umrah Visa')], max_length=2)),
                ('duration', models.CharField(choices=[('36', '36 Hours'), ('96', '96 Hours'), ('1m', '1 Month'), ('2m', '2 Months'), ('3m', '3 Months')], max_length=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ticket.customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ticket.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
