# Generated by Django 5.0 on 2023-12-22 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sale', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purchase', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField()),
                ('pnr', models.CharField(max_length=10)),
                ('sector', models.CharField(max_length=100)),
                ('travel_date', models.DateField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.airline')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.customer')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.passenger')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.supplier')),
            ],
        ),
    ]
