# Generated by Django 5.0 on 2023-12-23 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='current_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.airline'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.customer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.passenger'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.supplier'),
        ),
    ]
