# Generated by Django 5.0.1 on 2024-03-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_customer_user_ledger_user_supplier_user_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('IS', 'Issues'), ('RF', 'Refund'), ('RI', 'ReIssue'), ('VO', 'Void')], default='Issues', max_length=2),
        ),
    ]
