# Generated by Django 5.0.1 on 2024-04-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_issued_ticket_issued_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='roomrate',
            name='room_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Private'), (1, 'Sharing'), (2, 'Quadripple'), (3, 'Tripple'), (4, 'Double')]),
        ),
    ]
