# Generated by Django 5.0.1 on 2024-04-16 10:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_hotel_active_ledger_status_alter_roomrate_room_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(max_length=10)),
                ('sector', models.CharField(max_length=50)),
                ('departure', models.DateField(blank=True, null=True)),
                ('arrival', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('nights', models.PositiveIntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.roomrate')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hotels', models.ManyToManyField(through='ticket.HotelBooking', to='ticket.hotel')),
                ('trip', models.ManyToManyField(to='ticket.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visas', models.ManyToManyField(to='ticket.visa')),
            ],
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.voucher'),
        ),
    ]
