# Generated by Django 5.0.1 on 2024-04-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_trip_visa_pass_name_visa_pass_num_hotelbooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='pass_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visa',
            name='pass_num',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
