# Generated by Django 5.0.1 on 2024-03-15 10:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_ticket_ticket_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rial_price', models.PositiveIntegerField(blank=True, null=True)),
                ('pkr_price', models.PositiveIntegerField(blank=True, null=True)),
                ('sale', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('visa_type', models.CharField(choices=[('DV', 'Dubai Visit'), ('SV', 'Saudia Visit'), ('DW', 'Dubai Work'), ('SW', 'Saudia Work'), ('UV', 'Umrah Visa')], max_length=2)),
                ('duration', models.CharField(choices=[('36', '36 Hours'), ('96', '96 Hours'), ('1', '1 Month'), ('2', '2 Months')], max_length=2)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ticket.customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ticket.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
