# Generated by Django 5.0.1 on 2024-04-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_visa_pass_name_visa_pass_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='transport',
            field=models.BooleanField(default=False),
        ),
    ]
