# Generated by Django 5.0.1 on 2024-04-30 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_voucher_transport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='transaction_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Debit'), (1, 'Credit')], null=True),
        ),
        migrations.AlterField(
            model_name='visa',
            name='purchase',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='visa',
            name='purchase_pkr',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='visa',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='visa',
            name='sale_pkr',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='visa',
            name='visa_type',
            field=models.CharField(choices=[('DV', 'Dubai Visit'), ('SV', 'Saudia Visit'), ('DW', 'Dubai Work'), ('SW', 'Saudia Work'), ('UV', 'Umrah Visa'), ('HV', 'Hajj Visa')], max_length=2),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='visas',
            field=models.ManyToManyField(db_index=True, to='ticket.visa'),
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ledger',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='ticket.bank'),
        ),
    ]
