# Generated by Django 5.0.1 on 2024-03-16 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_rialprice_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visa',
            name='duration',
            field=models.CharField(choices=[('36', '36 Hours'), ('96', '96 Hours'), ('1m', '1 Month'), ('2m', '2 Months'), ('3m', '3 Months')], max_length=2),
        ),
    ]
