# Generated by Django 5.0 on 2024-01-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_ticket_airline_alter_ticket_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='airline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='purchase',
        ),
        migrations.AddField(
            model_name='ticket',
            name='purchase',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sale',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Airline',
        ),
    ]
