# Generated by Django 5.0 on 2024-01-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_alter_ledger_payment_date_alter_ticket_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='travel_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
