# Generated by Django 5.0.1 on 2024-02-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_alter_ticket_travel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='opening_balance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
