# Generated by Django 5.0.1 on 2024-02-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_alter_supplier_opening_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='opening_balance',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='opening_balance',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
