# Generated by Django 5.0.1 on 2024-02-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_ledger_description_alter_customer_opening_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
